---
- name: Add repository key
  apt_key:
    url: http://docs.mongodb.org/10gen-gpg-key.asc

- name: Add mongo repository
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main'

- name: Install mongodb package
  apt:
    name: mongodb-org

- name: check storage engine
  command: grep "storageEngine=wiredTiger" /etc/mongod.conf
  register: storage_engine
  ignore_errors: true

- name: use wiredTiger engine
  lineinfile:
    dest: /etc/mongod.conf
    line: 'storageEngine=wiredTiger'
  when: storage_engine|failed

- name: stop mongodb
  service:
    name: mongod
    state: stopped
  when: storage_engine|failed

- name: drop all files in old engine
  shell: rm -rf /var/lib/mongodb/*
  when: storage_engine|failed

- name: start mongodb
  service:
    name: mongod
    state: started
  when: storage_engine|failed

- name: listen at all interfaces
  lineinfile:
    dest: /etc/mongod.conf
    regexp: "^bind_ip"
    line: 'bind_ip = 0.0.0.0'
  notify:
    - restart mongodb
