---
- name: Install prereq
  apt:
    name: "{{ item }}"
  with_items:
    - "redis-server"
    - "nodejs"
    - "supervisor"
  tags:
    - install

- name: create shared directory structure
  file:
    state: directory
    owner: rbdev
    group: rbdev
    recurse: yes
    path: "{{ toprater_dir }}/shared/{{ item }}"
  with_items:
    - "config/puma"
    - "bin"
    - "log"
    - "tmp/pids"
    - "tmp/sockets"
    - "vendor/bundle"
    - "public/system"
  tags:
    - install

- name: Get release timestamp
  command: date +%Y%m%d%H%M%S
  register: timestamp
  tags:
    - deploy

- name: Name release directory
  command: echo "{{ toprater_dir }}/releases/{{ timestamp.stdout }}"
  register: release_path
  tags:
    - deploy

- name: Create release directory
  file:
    state: directory
    owner: rbdev
    group: rbdev
    recurse: yes
    path: "{{ release_path.stdout }}"
  tags:
    - deploy

- name: checkout git repo into release directory
  git:
    repo: ssh://git@github.com/Solver-Club/toprater.git
    dest: "{{ release_path.stdout }}"
    version: development
    accept_hostkey: yes
  tags:
    - deploy

- name: create other directory
  file:
    state: directory
    recurse: yes
    path: "{{ item }}"
  with_items:
    - "{{ release_path.stdout }}/vendor"
    - "{{ release_path.stdout }}/public"
  tags:
    - deploy

- name: delete bin directory
  file:
    state: absent
    path: "{{ release_path.stdout }}/bin"
  tags:
    - deploy

- name: link dirs
  file:
    state: link
    path: "{{ release_path.stdout }}/{{ item }}"
    src: "{{ toprater_dir }}/shared/{{ item }}"
  with_items:
    - "log"
    - "bin"
    - "tmp"
    - "vendor/bundle"
    - "public/system"
  tags:
    - deploy

- name: puma config
  template:
    src: "puma-config.yml.j2"
    dest: "{{ toprater_dir }}/shared/config/puma/{{ toprater_config.environment }}.yml"
    owner: rbdev
    group: rbdev
    mode: "0644"
  tags:
    - install

- name: create bundle dir
  file:
    state: directory
    owner: rbdev
    group: rbdev
    recurse: yes
    path: "{{ release_path.stdout }}/.bundle"
  tags:
    - deploy

- name: bundle config
  copy:
    src: toprater-bundle-config
    dest: "{{ release_path.stdout }}/.bundle/config"
  tags:
    - deploy

- name: ugly chown
  file:
    path: /home/rbdev
    owner: rbdev
    group: rbdev
    recurse: yes
  tags:
    - deploy

- name: install dependencies
  sudo_user: rbdev
  shell: cd {{ release_path.stdout }}; . {{ rbenv_path }}/.rbenvrc && bundle install
  tags:
    - deploy

- name: precompile assets
  sudo_user: rbdev
  shell: cd {{ release_path.stdout }}; . {{ rbenv_path }}/.rbenvrc && bundle exec rake assets:precompile RAILS_ENV={{ toprater_config.environment }}
  tags:
    - deploy

- name: update app version
  file:
    state: link
    path: "{{ toprater_dir }}/current"
    src: "{{ release_path.stdout }}"
  tags:
    - deploy

- name: add supervisor config
  template:
    src: "supervisor-toprater.conf.j2"
    dest: "/etc/supervisor/conf.d/toprater.conf"
  tags:
    - install
    - deploy

- name: reread supervisorctl
  shell: /usr/bin/supervisorctl reread && /usr/bin/supervisorctl update && /usr/bin/supervisorctl stop toprater && /usr/bin/supervisorctl clear toprater && /usr/bin/supervisorctl remove toprater && /usr/bin/supervisorctl add toprater
  tags:
    - deploy
