---
- hosts: megarulez
  sudo: no
  tasks:
  - name: init py mysql
    apt:
      name: python-mysqldb
      state: present
  - name: take date
    command: date -Idate
    register: date
  - local_action: command echo item
    with_items: date.stdout_lines
  - name: backup database
    notify: fetch dump
    mysql_db:
      state: dump
      name: "{{ vault_mysql_db }}"
      target: "/root/{{ date['stdout'] }}.sql.gz"
      login_host: localhost
      login_user: "{{ vault_mysql_login }}"
      login_password: "{{ vault_mysql_password }}"
  handlers:
  - name: fetch dump
    fetch:
      src: "/root/{{ date['stdout'] }}.sql.gz"
      dest: "/tmp/"
