---
- hosts: megarulez
  sudo: no
  tasks:
    - name: stop
      service: name={{ item }} state=stopped
      with_items:
        - apache2
        - mysql
    - name: start
      service: name={{ item }} state=started
      with_items:
        - mysql
        - apache2
