---
- name: Install prerequisite packages
  apt:
    name: "{{ item }}"
  with_items:
    - "supervisor"
  tags:
    - install

- name: create shared directory structure
  file:
    state: directory
    owner: rbdev
    group: rbdev
    recurse: yes
    path: "{{ knock_dir }}/shared/{{ item }}"
  with_items:
    - "bin"
    - "bundle"
    - "config/thin"
    - "log"
    - "public/system"
    - "tmp/pids"
    - "tmp/sockets"
    - "vendor/bundle"
  tags:
    - install

- name: Get release timestamp
  command: date +%Y%m%d%H%M%S
  register: timestamp
  tags:
    - deploy

- name: Name release directory
  command: echo "{{ knock_dir }}/releases/{{ timestamp.stdout }}"
  register: release_path
  tags:
    - deploy

- name: Create release directory
  file:
    state: directory
    owner: rbdev
    group: rbdev
    recurse: yes
    path: "{{ release_path.stdout }}"
  tags:
    - deploy

- name: checkout git repo into release directory
  git:
    repo: ssh://git@github.com/Solver-Club/knock.git
    dest: "{{ release_path.stdout }}"
    version: "{{ release_tag }}"
    accept_hostkey: yes
  tags:
    - deploy

- name: create other directory
  file:
    state: directory
    recurse: yes
    path: "{{ item }}"
  with_items:
    - "{{ release_path.stdout }}/vendor"
    - "{{ release_path.stdout }}/public"
  tags:
    - deploy

- name: copy db config to shared
  template:
    src: "database.yml.j2"
    dest: "{{ knock_dir }}/shared/config/database.yml"
  tags:
    - deploy
    - config

- name: delete bin dir and config/database.yml
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ release_path.stdout }}/bin"
    - "{{ release_path.stdout }}/config/database.yml"
  tags:
    - deploy

- name: link
  file:
    state: link
    path: "{{ release_path.stdout }}/{{ item }}"
    src: "{{ knock_dir }}/shared/{{ item }}"
  with_items:
    - "log"
    - "bin"
    - "tmp"
    - "vendor/bundle"
    - "public/system"
    - "config/database.yml"
  tags:
    - deploy

- name: thin config
  template:
    src: "thin-config.yml.j2"
    dest: "{{ knock_dir }}/shared/config/thin/{{ environment }}.yml"
    owner: rbdev
    group: rbdev
    mode: "0644"
  tags:
    - install
    - config

- name: create bundle dir
  file:
    state: directory
    owner: rbdev
    group: rbdev
    recurse: yes
    path: "{{ release_path.stdout }}/.bundle"
  tags:
    - deploy

- name: bundle config
  copy:
    src: knock-bundle-config
    dest: "{{ release_path.stdout }}/.bundle/config"
  tags:
    - deploy

- name: ugly chown
  file:
    path: /home/rbdev
    owner: rbdev
    group: rbdev
    recurse: yes
  tags:
    - deploy

- name: install dependencies
  sudo: yes
  sudo_user: rbdev
  shell: cd {{ release_path.stdout }}; . {{ rbenv_path }}/.rbenvrc && bundle install
  tags:
    - deploy

#- name: run db migrations
#  sudo: yes
#  sudo_user: rbdev
#  shell: cd {{ release_path.stdout }}; . {{ rbenv_path }}/.rbenvrc && bundle exec rake db:migrate RAILS_ENV={{ environment }}
#  tags:
#    - deploy

- name: update app version
  file:
    state: link
    path: "{{ knock_dir }}/current"
    src: "{{ release_path.stdout }}"
  tags:
    - deploy

- name: add supervisor config
  template:
    src: "supervisor-knock.conf.j2"
    dest: "/etc/supervisor/conf.d/knock.conf"
  tags:
    - install

#- name: reread supervisorctl
#  shell: /usr/bin/supervisorctl reread && /usr/bin/supervisorctl knock && /usr/bin/supervisorctl stop crowd && /usr/bin/supervisorctl clear crowd && /usr/bin/supervisorctl remove crowd && /usr/bin/supervisorctl add crowd
#  tags:
#    - deploy
#    - config
