Vagrant.configure(2) do |config|
  config.vm.box = "wheezy"
  config.ssh.username = "root"
  config.ssh.forward_agent = true

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "frontend.yml"
    ansible.verbose = 'vv'
    ansible.extra_vars = { ansible_ssh_user: 'root',
                 ansible_connection: 'ssh',
                 ansible_ssh_args: '-o ForwardAgent=yes -o UserKnownHostsFile=/dev/null'}
  end
end
