---
- name: add repository key
  apt_key:
    url: https://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: add elasticsearch repository
  apt_repository:
    repo: 'deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main'
    state: present

- name: install elasticsearch package
  apt:
    name: elasticsearch=1.4.0

- name: set script.disable_dynamic in config
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: "^script.disable_dynamic"
    insertafter: EOF
    line: 'script.disable_dynamic:\t false'
    create: yes

- name: set ES_HEAP_SIZE
  lineinfile:
    dest: /etc/init.d/elasticsearch
    regexp: "^#ES_HEAP_SIZE="
    line: 'ES_HEAP_SIZE=10g'

- name: add elasticsearch to autostart
  shell: update-rc.d elasticsearch defaults 95 10

- name: install aws cloud plugin
  shell: /usr/share/elasticsearch/bin/plugin install elasticsearch/elasticsearch-cloud-aws/2.4.1

- name: set publish_address
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: "^#network.publish_host"
    line: "network.publish_host: _ec2:publicIpv4_"
    create: yes

- name: restart elasticsearch service
  service:
    name: elasticsearch
    state: restarted
    enabled: yes

