---
- name: restart mongodb
  service:
    name: mongod
    state: restarted

- name: stop mongodb
  service:
    name: mongod
    state: stopped

- name: start mongodb
  service:
    name: mongod
    state: started

- name: drop mongo database
  shell: rm -f /var/lib/mongodb/*
